### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Hikahon** [Hikahon/furima-39145#20]
# URL
https://furima-39145.onrender.com/

# Basic認証のIDとパスワード
BASIC_AUTH_USER= 177d63dcd1664400d5e9658a001d4769
BASIC_AUTH_PASSWORD= 124c95cacd1e0c80cff12886d4329d4f

# 出品者用のメールアドレスとパスワード
メールアドレス：cat@mail
パスワード：cat123

# 購入者用のメールアドレスとパスワード
メールアドレス：dog@mail
パスワード：dog123

**Comment by shodai-ito** [comment]
@Hikahon さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`購入機能`**
- [ ] **エラーハンドリングの際、重複したエラーメッセージが表示されないこと**
電話番号についてのエラーメッセージに重複がありました。
<img width="552" alt="スクリーンショット 2023-09-10 9 25 21" src="https://github.com/Hikahon/furima-39145/assets/62537107/ec10d910-38f5-4c42-9f1d-e046543c6dd2">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shodai-ito** [comment]
@Hikahon さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
